### ISSUE TITLE
请问后台项目地址在哪 想参考下 谢谢

### ISSUE THREAD

**Issue by zuorichongxian** [zhongku/mpvue-weex#2]

**Comment by zhongku** [comment]
src/service/api/config.js

**Comment by zuorichongxian** [comment]
![diy](https://user-images.githubusercontent.com/24955179/43121170-6a01d550-8f4f-11e8-8c73-27247f43d29a.jpg)

我想问的是这个后台管理的仓库地址

**Comment by yuangu** [comment]
你们有没有提示网络错误？编译之类的都没有报错。就是一片白，看不到界面

**Comment by JokerLoLgrey** [comment]
楼上的，我遇到了

**Comment by haotian2546** [comment]
没有可请求的接口地址啊

**Comment by 2716918694** [comment]
这前端项目没有后端服务器就不能显示？大牛能来个捕获异常吗

**Comment by 2716918694** [comment]
这个项目前后端耦合在一起的！前台跳转路径是后台传值？

**Comment by TenzeTseng** [comment]
需要付费早说嘛

**Comment by TenzeTseng** [comment]
商业化的东西就不要放上来吸眼球了，  连官网的注册登录授权都用不了， 还能让人相信你这里的玩意？

**Comment by yhbme123456** [comment]
你们有没有提示网络错误？编译之类的都没有报错。就是一片白，看不到界面

**Comment by ghost** [comment]
所以楼上的大佬们谁解决了没？

**Comment by fanyangh** [comment]
所以 我想问问有没有后端项目地址 我想跑起来看看 这个代码有点意思

**Comment by fanyangh** [comment]
所以 我想问问有没有后端项目地址 我想跑起来看看 这个代码有点意思

> 这个项目前后端耦合在一起的！前台跳转路径是后台传值？

目测路径是后端给的
