### ISSUE TITLE
erro # build H5 pages npm run dev

### ISSUE THREAD

**Issue by marcelowu** [zhongku/mpvue-weex#4]
![2](https://user-images.githubusercontent.com/30912144/44625934-008f3900-a8ea-11e8-8e5b-d9398d7c23d7.PNG)
![1](https://user-images.githubusercontent.com/30912144/44625940-0422c000-a8ea-11e8-9279-b03d8fce7c32.PNG)

**Comment by marcelowu** [comment]
network error...

**Comment by zhitrend** [comment]
同上，再有iOS项目启动时BMBaseLibrary的组件库可能比较旧了，友盟的部分头文件找不到
