### ISSUE TITLE
现有代码构建小程序和app失败

### ISSUE THREAD

**Issue by ssqyht** [zhongku/mpvue-weex#5]
请问可以提供可以编译正常的 脚手架吗，我只需要脚手架 不需要关于页面的配置 我会手写页面？ 错误信息如下

ERROR in ./src/_start/app/main.js
Module not found: Error: Can't resolve './App' in '/Users/yuanhaitao/git/micro/mpvue-weex/src/_start/app'
 @ ./src/_start/app/main.js 3:0-24

ERROR in ./src/_start/app/main.js
Module not found: Error: Can't resolve '@/router' in '/Users/yuanhaitao/git/micro/mpvue-weex/src/_start/app'
 @ ./src/_start/app/main.js 4:0-30

ERROR in ./src/_start/app/main.js
Module not found: Error: Can't resolve '@/service/api' in '/Users/yuanhaitao/git/micro/mpvue-weex/src/_start/app'
 @ ./src/_start/app/main.js 12:0-36

**Comment by ssqyht** [comment]
@zhongku

**Comment by xixichensh** [comment]
我也有遇到
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/Users/xxxx/Workspace/GitHub/MpvueWeex/src/router/routes.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
