### ISSUE TITLE
所以这是一个盒子？用来显示服务端渲染的H5以及APP内嵌服务器渲染网页的项目？这不是骗星星嘛？

### ISSUE THREAD

**Issue by Eden-Harris** [zhongku/mpvue-weex#8]

**Comment by cococa** [comment]
weex 了解下，app 都是用weex 来调用 native 渲染

**Comment by Eden-Harris** [comment]
> weex 了解下，app 都是用weex 来调用 native 渲染

你运行出来的this.pageInfo是什么？weex打包 和  APP端全部由weex 渲染是一个意思吗？你有看出来可用的weex组件有多少吗？

**Comment by cococa** [comment]
> > weex 了解下，app 都是用weex 来调用 native 渲染
> 
> 你运行出来的this.pageInfo是什么？weex打包 和 APP端全部由weex 渲染是一个意思吗？你有看出来可用的weex组件有多少吗？

人家本来就是用一套vue代码 转 小程序，h5，weex（ios和 android），Android 代码里用的就是weex 的 lib ，看下面的链接，你去看weex的官网介绍（Weex 是一个可以使用现代化的 Web 技术开发高性能原生应用的框架。） 你标题中所说的APP内嵌服务器渲染网页的项目，不就是想说他是app 用 webview套h5 吗？但是真的不是，好好去看下weex的文档，自己看下weex 项目中的ios 和android的实现，每一个web的标签都对应了原生的控件

https://github.com/zhongku/mpvue-weex/blob/0da6a61cc167b969c6e8c9d2dac826984ea13cf3/platforms/android/WeexFrameworkWrapper/sdk/src/main/java/com/taobao/weex/WXSDKManager.java

**Comment by Eden-Harris** [comment]
> > > weex 了解下，app 都是用weex 来调用 native 渲染
> > 
> > 
> > 你运行出来的this.pageInfo是什么？weex打包 和 APP端全部由weex 渲染是一个意思吗？你有看出来可用的weex组件有多少吗？
> 
> 人家本来就是用一套vue代码 转 小程序，h5，weex（ios和 android），Android 代码里用的就是weex 的 lib ，看下面的链接，你去看weex的官网介绍（Weex 是一个可以使用现代化的 Web 技术开发高性能原生应用的框架。） 你标题中所说的APP内嵌服务器渲染网页的项目，不就是想说他是app 用 webview套h5 吗？但是真的不是，好好去看下weex的文档，自己看下weex 项目中的ios 和android的实现，每一个web的标签都对应了原生的控件
> 
> https://github.com/zhongku/mpvue-weex/blob/0da6a61cc167b969c6e8c9d2dac826984ea13cf3/platforms/android/WeexFrameworkWrapper/sdk/src/main/java/com/taobao/weex/WXSDKManager.java

我用weex时间也不短了，weex的实现你不用给我扯，我们讨论的是这个项目，不是阿里巴巴推出的weex项目。 你如果对这个项目很有把握，你跑一个出来给我试试，Android 渲染的界面截图给我或者给大家看看。我不是对你有意见，也不是对开源项目有意见，我是对根本不是开源项目而冒充一个开源项目且描述功能或者特性依照现有代码根本无法呈现而觉得很不合适，你不要一上来就给我一通乱咬。
你要是看了我回复你的话可以选择回复一下，否则我会在明天12点关闭这个issues而避免和你做无意义且牛头不对马嘴的讨论

**Comment by Eden-Harris** [comment]
> > > > weex 了解下，app 都是用weex 来调用 native 渲染
> > > 
> > > 
> > > 你运行出来的this.pageInfo是什么？weex打包 和 APP端全部由weex 渲染是一个意思吗？你有看出来可用的weex组件有多少吗？
> > 
> > 
> > 人家本来就是用一套vue代码 转 小程序，h5，weex（ios和 android），Android 代码里用的就是weex 的 lib ，看下面的链接，你去看weex的官网介绍（Weex 是一个可以使用现代化的 Web 技术开发高性能原生应用的框架。） 你标题中所说的APP内嵌服务器渲染网页的项目，不就是想说他是app 用 webview套h5 吗？但是真的不是，好好去看下weex的文档，自己看下weex 项目中的ios 和android的实现，每一个web的标签都对应了原生的控件
> > https://github.com/zhongku/mpvue-weex/blob/0da6a61cc167b969c6e8c9d2dac826984ea13cf3/platforms/android/WeexFrameworkWrapper/sdk/src/main/java/com/taobao/weex/WXSDKManager.java
> 
> 我用weex时间也不短了，weex的实现你不用给我扯，我们讨论的是这个项目，不是阿里巴巴推出的weex项目。 你如果对这个项目很有把握，你跑一个出来给我试试，Android 渲染的界面截图给我或者给大家看看。我不是对你有意见，也不是对开源项目有意见，我是对根本不是开源项目而冒充一个开源项目且描述功能或者特性依照现有代码根本无法呈现而觉得很不合适，你不要一上来就给我一通乱咬。
> 你要是看了我回复你的话可以选择回复一下，否则我会在明天12点关闭这个issues而避免和你做无意义且牛头不对马嘴的讨论

唉，算了算了，给你讨论搞球用，说一百遍，这个项目也是运行不起的，我关闭这个issues吧，免得心烦
